import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import styles from './MainLayout.module.css'
import { NavBar } from '../NavBar'

export const MainLayout = ({ children }) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>0
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <main className={styles.main}>
                {children}
            </main>

        </div>
    )
}
